---
# Playbook file

- name: osx
  hosts: laptop
  roles:
    - osx

- name: brew
  hosts: laptop
  roles:
    - brew

- name: casks
  hosts: laptop
  roles:
    - casks

- name: dotfiles
  hosts: laptop
  roles:
    - dotfiles

- name: vim
  hosts: laptop
  roles:
    - vim
